(define (pascal m n)
  (cond ((and (= m 1) (= n 1)) 1)
        ((= n 1) (pascal (- m 1) 1))
        ((= n m) (pascal (- m 1) (- n 1)))
        (else (+ (pascal (- m 1) (- n 1)) (pascal (- m 1) n)))
  )
)

(pascal 1 1)
(pascal 2 1)
(pascal 2 2)
(pascal 3 1)
(pascal 3 2)
(pascal 3 3)
(pascal 4 1)
(pascal 4 2)
(pascal 4 3)
(pascal 4 4)
